version: '3.5'
name: "Sync_bridges-services"
services:
  db:
    image: "postgres"
    restart: always
    container_name: Sync_bridges-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "sync-bridges"
      POSTGRES_PASSWORD: "password"
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "8010:5432"

volumes:
  database-data: